
import { RestorationSite } from './restoration-site';

export const SITES: RestorationSite[] = [
    {
        "Map_ID": "DES01",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 260,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "PSNERP Preliminary Design",
        "Polygon_Source_GIS": "PSNERP",
        "Polygon_Note": "Notes",
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DOS01",
        "Status": "ACTIVE",
        "Year_Complete": 2015,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "P. Cereghino",
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DOS04",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - No acres opened ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DUC01",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 2.93,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": "PSNERP",
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DUN01",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 25.4,
        "Source_of_Acreage_Estimate": "30% Design Document",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DUN09",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": null,
        "Acres": 130,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DUN03",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 8,
        "Source_of_Acreage_Estimate": "Five acres from duck-hunting club property, three acres on WDFW property. Found in Final project report in PRISM.",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "ELW01",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": 6.4,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NSQ01",
        "Status": "COMPLETE",
        "Year_Complete": 1996,
        "New_Tidal_Flood": "X",
        "Acres": 9,
        "Source_of_Acreage_Estimate": "Supporting documents by Ellings",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NSQ02",
        "Status": "COMPLETE",
        "Year_Complete": 2003,
        "New_Tidal_Flood": "X",
        "Acres": 31,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NSQ03",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 100,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NSQ04",
        "Status": "COMPLETE",
        "Year_Complete": 2009,
        "New_Tidal_Flood": "X",
        "Acres": 762,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NSQ06",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Confirmed at LE Interview - no additional acreage should be claimed",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NKS02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 161.5,
        "Source_of_Acreage_Estimate": "747 number too high.  PRISM record claims 160.5",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NKS11",
        "Status": "COMPLETE",
        "Year_Complete": 2004,
        "New_Tidal_Flood": "NO",
        "Acres": 55,
        "Source_of_Acreage_Estimate": "PRISM (report varies between data and final report)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "NKS08",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1200,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL01",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 3.42,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL02",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 14.29,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL03",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 5.84,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL04",
        "Status": "COMPLETE",
        "Year_Complete": 2003,
        "New_Tidal_Flood": "X",
        "Acres": 4.77,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 21.49,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "QUL13",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "NO",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG11",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 131,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG01",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 37,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG02",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "X",
        "Acres": 212,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG04",
        "Status": "COMPLETE",
        "Year_Complete": 2009,
        "New_Tidal_Flood": "X",
        "Acres": 156,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG12",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 60,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG16\nSKG17\nSKT18",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 204,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG22",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG30",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 18.48,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG31",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 5.81,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG32",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 172,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG09",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 268.11,
        "Source_of_Acreage_Estimate": "?",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKG26",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKO01",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 115.68,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKO02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 214.93,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SKO05",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "PRISM Acres of Estuary Created",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO02",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 350,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO05",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 320,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO06",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 74,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO07",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 326,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO13",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 21.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO14",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 230,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO04",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 19.3,
        "Source_of_Acreage_Estimate": "Website",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO10",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 93,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO11",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 400,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO15",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1237,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "SNO16",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 829,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "STL04",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 83,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "STL06",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 150,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "STL03",
        "Status": "COMPLETE",
        "Year_Complete": 2013,
        "New_Tidal_Flood": "X",
        "Acres": 150,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Levee_R/M"
    },
    {
        "Map_ID": "DOS01",
        "Status": "ACTIVE",
        "Year_Complete": 2015,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "P. Cereghino",
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "DOS04",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - No acres opened ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "DOS06",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - No acres opened ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "DUW08",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "X",
        "Acres": 1.55,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "DUW10",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "ELW02",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": 80,
        "Source_of_Acreage_Estimate": "HWS ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "HAM02",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 2.38,
        "Source_of_Acreage_Estimate": "Hood Canal Metric Summary: Acres opened to tidal processes",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "PUY01",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 2.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "PUY20",
        "Status": "COMPLETE",
        "Year_Complete": -1,
        "New_Tidal_Flood": null,
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "PUY21",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11.5,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "QUL03",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 5.84,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "QUL04",
        "Status": "COMPLETE",
        "Year_Complete": 2003,
        "New_Tidal_Flood": "X",
        "Acres": 4.77,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "QUL06",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 7.01,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "QUL07",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "SKG01",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 37,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "SNO07",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 326,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "SNO25",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "SNO15",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1237,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "LWD/ELJ_Addition"
    },
    {
        "Map_ID": "DOS09",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 0.2,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DOS04",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - No acres opened ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DOS05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 4.68,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - Acres opened to tidal processes",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DOS06",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - No acres opened ",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DOS07",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 5.14,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - Acres opened to tidal processes",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUC05",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 2,
        "Source_of_Acreage_Estimate": "Hood Canal Three Year Workplan",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUN01",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 25.4,
        "Source_of_Acreage_Estimate": "30% Design Document",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUN02",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Mostly acquisition, no dike removal",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUN03",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 8,
        "Source_of_Acreage_Estimate": "Five acres from duck-hunting club property, three acres on WDFW property. Found in Final project report in PRISM.",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW01",
        "Status": "COMPLETE",
        "Year_Complete": 1997,
        "New_Tidal_Flood": "X",
        "Acres": 0.6,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW02",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 3.44,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW04",
        "Status": "COMPLETE",
        "Year_Complete": 2014,
        "New_Tidal_Flood": "X",
        "Acres": 2.42,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW13",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 3,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW11",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DUW10",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "NSQ04",
        "Status": "COMPLETE",
        "Year_Complete": 2009,
        "New_Tidal_Flood": "X",
        "Acres": 762,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "NSQ06",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Confirmed at LE Interview - no additional acreage should be claimed",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "NKS02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 161.5,
        "Source_of_Acreage_Estimate": "747 number too high.  PRISM record claims 160.5",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY01",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 2.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY07",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 0.66,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY08",
        "Status": "COMPLETE",
        "Year_Complete": 1996,
        "New_Tidal_Flood": "X",
        "Acres": 3.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY14",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 15.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY20",
        "Status": "COMPLETE",
        "Year_Complete": -1,
        "New_Tidal_Flood": null,
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY21",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11.5,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "PUY02\nPUY03\nPUY04\nPUY05",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": null,
        "Acres": 2,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "QUL01",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 3.42,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "QUL02",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 14.29,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "QUL05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 21.49,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "QUL07",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SSN04",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11,
        "Source_of_Acreage_Estimate": "PRISM 04-1649 Removal of existing fill material",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG01",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 37,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG02",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "X",
        "Acres": 212,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG04",
        "Status": "COMPLETE",
        "Year_Complete": 2009,
        "New_Tidal_Flood": "X",
        "Acres": 156,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG20",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG27",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "NO",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKG09",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 268.11,
        "Source_of_Acreage_Estimate": "?",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKO03",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 33.51,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SKO05",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "PRISM Acres of Estuary Created",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO02",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 350,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO05",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 320,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO07",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 326,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO13",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 21.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO03",
        "Status": "COMPLETE",
        "Year_Complete": 1994,
        "New_Tidal_Flood": "X",
        "Acres": 3,
        "Source_of_Acreage_Estimate": "Website",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO25",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "SNO01",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 10,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "UNIO5",
        "Status": "ACTIVE",
        "Year_Complete": 2016,
        "New_Tidal_Flood": "X",
        "Acres": 7.3,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Re-vegetation"
    },
    {
        "Map_ID": "DOS09",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 0.2,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DOS05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 4.68,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - Acres opened to tidal processes",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DOS10",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 12,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUC02",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 38,
        "Source_of_Acreage_Estimate": "PSNERP",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUC05",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 2,
        "Source_of_Acreage_Estimate": "Hood Canal Three Year Workplan",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW05",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 0.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW01",
        "Status": "COMPLETE",
        "Year_Complete": 1997,
        "New_Tidal_Flood": "X",
        "Acres": 0.6,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW02",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 3.44,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW04",
        "Status": "COMPLETE",
        "Year_Complete": 1999,
        "New_Tidal_Flood": "X",
        "Acres": 1.7,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW04",
        "Status": "COMPLETE",
        "Year_Complete": 2014,
        "New_Tidal_Flood": "X",
        "Acres": 2.42,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW08",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "X",
        "Acres": 1.55,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW13",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 3,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW11",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUW10",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "PUY01",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 2.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "PUY07",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 0.66,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "PUY09",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 1.9,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "PUY21",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11.5,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "PUY15",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1.4,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "QUL04",
        "Status": "COMPLETE",
        "Year_Complete": 2003,
        "New_Tidal_Flood": "X",
        "Acres": 4.77,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "QUL06",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 7.01,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SSN05",
        "Status": "ACTIVE",
        "Year_Complete": 2015,
        "New_Tidal_Flood": "X",
        "Acres": 1.5,
        "Source_of_Acreage_Estimate": "PRISM Summary",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SSN06",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 13,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SSN04",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11,
        "Source_of_Acreage_Estimate": "PRISM 04-1649 Removal of existing fill material",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SKG24",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 43,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SKG35",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SKO01",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 115.68,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SKO02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 214.93,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SNO25",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "SNO15",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1237,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "UNIO5",
        "Status": "ACTIVE",
        "Year_Complete": 2016,
        "New_Tidal_Flood": "X",
        "Acres": 7.3,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Fill_removal"
    },
    {
        "Map_ID": "DUC02",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 38,
        "Source_of_Acreage_Estimate": "PSNERP",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "DUW01",
        "Status": "COMPLETE",
        "Year_Complete": 1997,
        "New_Tidal_Flood": "X",
        "Acres": 0.6,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "DUW02",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 3.44,
        "Source_of_Acreage_Estimate": "LE (Blueprint)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "HAM02",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 2.38,
        "Source_of_Acreage_Estimate": "Hood Canal Metric Summary: Acres opened to tidal processes",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "NKS02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 161.5,
        "Source_of_Acreage_Estimate": "747 number too high.  PRISM record claims 160.5",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "NKS11",
        "Status": "COMPLETE",
        "Year_Complete": 2004,
        "New_Tidal_Flood": "NO",
        "Acres": 55,
        "Source_of_Acreage_Estimate": "PRISM (report varies between data and final report)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY07",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 0.66,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY08",
        "Status": "COMPLETE",
        "Year_Complete": 2000,
        "New_Tidal_Flood": "X",
        "Acres": 1.9,
        "Source_of_Acreage_Estimate": "Monitoring Report",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY14",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 15.3,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY21",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11.5,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY02\nPUY03\nPUY04\nPUY05",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": null,
        "Acres": 2,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "PUY16",
        "Status": "OTHER",
        "Year_Complete": -1,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "QUL01",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 3.42,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "QUL05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 21.49,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "QUL06",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 7.01,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "QUL07",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SSN05",
        "Status": "ACTIVE",
        "Year_Complete": 2015,
        "New_Tidal_Flood": "X",
        "Acres": 1.5,
        "Source_of_Acreage_Estimate": "PRISM Summary",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SSN06",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 13,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SKG01",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 37,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SKG02",
        "Status": "COMPLETE",
        "Year_Complete": 2012,
        "New_Tidal_Flood": "X",
        "Acres": 212,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SKO03",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 33.51,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SKO01",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 115.68,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SKO02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 214.93,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO02",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 350,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO05",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 320,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO06",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 74,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO07",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 326,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO12",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 10.4,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO13",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 21.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO04",
        "Status": "COMPLETE",
        "Year_Complete": 2001,
        "New_Tidal_Flood": "X",
        "Acres": 19.3,
        "Source_of_Acreage_Estimate": "Website",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO10",
        "Status": "COMPLETE",
        "Year_Complete": 2006,
        "New_Tidal_Flood": "X",
        "Acres": 93,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO15",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1237,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "SNO16",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 829,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Channel_Excavation"
    },
    {
        "Map_ID": "DUN02",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "Mostly acquisition, no dike removal",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "DUW05",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 0.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "DUW12",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 20,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "NKS02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 161.5,
        "Source_of_Acreage_Estimate": "747 number too high.  PRISM record claims 160.5",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "NKS11",
        "Status": "COMPLETE",
        "Year_Complete": 2004,
        "New_Tidal_Flood": "NO",
        "Acres": 55,
        "Source_of_Acreage_Estimate": "PRISM (report varies between data and final report)",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "NKS08",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1200,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "NKS08",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "NO",
        "Acres": null,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "PUY18",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "NO",
        "Acres": 17,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "SKG01",
        "Status": "COMPLETE",
        "Year_Complete": 2005,
        "New_Tidal_Flood": "X",
        "Acres": 37,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "SKG27",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "NO",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "SNO14",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 230,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "SNO15",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 1237,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "STL04",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 83,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "STL06",
        "Status": "ACTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 150,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "STL05",
        "Status": "OTHER",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Acquisition"
    },
    {
        "Map_ID": "DUN05",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 300,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "NKS02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 161.5,
        "Source_of_Acreage_Estimate": "747 number too high.  PRISM record claims 160.5",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKG04",
        "Status": "COMPLETE",
        "Year_Complete": 2009,
        "New_Tidal_Flood": "X",
        "Acres": 156,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKG12",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 60,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKG24",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 43,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKO01",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 115.68,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKO02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 214.93,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SKO05",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "PRISM Acres of Estuary Created",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SNO07",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 326,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SNO13",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 21.6,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "SNO11",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 400,
        "Source_of_Acreage_Estimate": "PRISM",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Tidegate_R/M"
    },
    {
        "Map_ID": "DOS05",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 4.68,
        "Source_of_Acreage_Estimate": "Hood Canal Metrics Report - Acres opened to tidal processes",
        "Polygon_Source": "HWS",
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "DOS08",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 2,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "DOS10",
        "Status": "CONCEPTUAL",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 12,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "HCCC",
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "DUC02",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "X",
        "Acres": 38,
        "Source_of_Acreage_Estimate": "PSNERP",
        "Polygon_Source": null,
        "Polygon_Source_GIS": "P. Cereghino",
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "DUC03",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "NO",
        "Acres": 0,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "DUW10",
        "Status": "PROSPECTIVE",
        "Year_Complete": -1,
        "New_Tidal_Flood": "?",
        "Acres": -9999,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "HAM02",
        "Status": "COMPLETE",
        "Year_Complete": 2010,
        "New_Tidal_Flood": "X",
        "Acres": 2.38,
        "Source_of_Acreage_Estimate": "Hood Canal Metric Summary: Acres opened to tidal processes",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "PUY21",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 11.5,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "QUL02",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 14.29,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SKG24",
        "Status": "COMPLETE",
        "Year_Complete": 2008,
        "New_Tidal_Flood": "X",
        "Acres": 43,
        "Source_of_Acreage_Estimate": null,
        "Polygon_Source": "PRISM",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SKO03",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 33.51,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SKO01",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 115.68,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SKO02",
        "Status": "COMPLETE",
        "Year_Complete": 2011,
        "New_Tidal_Flood": "X",
        "Acres": 214.93,
        "Source_of_Acreage_Estimate": "LE",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SKO05",
        "Status": "COMPLETE",
        "Year_Complete": 2007,
        "New_Tidal_Flood": "X",
        "Acres": 0,
        "Source_of_Acreage_Estimate": "PRISM Acres of Estuary Created",
        "Polygon_Source": null,
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SNO02",
        "Status": "COMPLETE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 350,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    },
    {
        "Map_ID": "SNO12",
        "Status": "ACTIVE",
        "Year_Complete": 0,
        "New_Tidal_Flood": "X",
        "Acres": 10.4,
        "Source_of_Acreage_Estimate": "HWS",
        "Polygon_Source": "LE Map",
        "Polygon_Source_GIS": null,
        "Polygon_Note": null,
        "Action": "Culvert_R/M"
    }
];

